---
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resource-cleanup-policy.serviceAccountName" . }}
rules:

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
    verbs:
      - "list"
      - "watch"
  - apiGroups:
      - "neo9.io"
    resources:
      - "resources-cleanup-policy"
      - "pods-cleanup-policy"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - "list"
      - "watch"

  # Framework: admission webhook configuration management.
  - apiGroups:
      - "admissionregistration.k8s.io"
      - "admissionregistration.k8s.io/v1"
      - "admissionregistration.k8s.io/v1beta1"
    resources:
      - "validatingwebhookconfigurations"
      - "mutatingwebhookconfigurations"
    verbs:
      - "create"
      - "patch"

  # Events
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - "*"
      - "list"
      - "create"

   # Pods cleanup
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "list"
      - "get"
      - "watch"
      - "delete"

   # Jobs cleanup
  - apiGroups:
      - "batch"
    resources:
      - "jobs"
    verbs:
      - "list"
      - "get"
      - "watch"
      - "delete"

   # Tekton cleanup
  - apiGroups:
      - "tekton.dev"
    resources:
      - "pipelineruns"
      - "taskruns"
    verbs:
      - "list"
      - "get"
      - "watch"
      - "delete"


{{- end }}

---
{{- if and .Values.rbac.create .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resource-cleanup-policy.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "resource-cleanup-policy.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource-cleanup-policy.serviceAccountName" . }}
    namespace: "{{ .Release.Namespace}}"
{{- end }}
