apiVersion: v1
appVersion: 1.3.5
description: A Helm chart for installing PrivateBin
home: https://privatebin.info/
icon: https://raw.githubusercontent.com/PrivateBin/assets/master/images/preview/icon.png
keywords:
- pastebin
- PrivateBin
- ZeroBin
name: privatebin
sources:
- https://github.com/PrivateBin/PrivateBin
- https://github.com/PrivateBin/docker-nginx-fpm-alpine
version: 0.9.0
